### ISSUE TITLE
Supported device

### ISSUE THREAD

**Issue by ioukos** [pvvx/BLE_THSensor#11]
Is this device supported ?

https://fr.aliexpress.com/item/1005005595631552.html?spm=a2g0n.detail.1000014.2.1ae5MsDhMsDhk3&gps-id=platformRecommendH5&scm=1007.18499.332340.0&scm_id=1007.18499.332340.0&scm-url=1007.18499.332340.0&pvid=247caeec-aa67-4987-b7bb-69c2fcbbaf6b&_t=gps-id:platformRecommendH5,scm-url:1007.18499.332340.0,pvid:247caeec-aa67-4987-b7bb-69c2fcbbaf6b,tpp_buckets:668%232846%238110%231995&pdp_npi=4%40dis%21EUR%218.82%213.79%21%21%219.38%214.03%21%40211b812f17107993322802471efc0c%2112000033689019997%21rec%21FR%211862277373%21

I want to use with BLE protocol. Should I buy zigbee or Wi-Fi ? as I will have to push firmware using serial I think it doesn't matter.

Regardd

**Comment by pvvx** [comment]
The seller you specified is overpriced by 2 times.

Only Zigbee option. WiFi uses a different chip.
