### ISSUE TITLE
Can’t update from TelinkMiFlasher

### ISSUE THREAD

**Issue by Toniob** [pvvx/BLE_THSensor#12]
Hello,

It seems I can’t update the sensor with the button on the Telink Flasher webpage. If I click on "Custom firmware : TS0201_v47.bin", nothing happens.

![Screenshot_20240411-122829](https://github.com/pvvx/BLE_THSensor/assets/113461/8291a4c7-7975-4d09-826f-49b9c499ad35)

Any idea ?

Thanks

**Comment by pvvx** [comment]
Fixed. The TS0201_v47.bin file has been restored.

**Comment by Toniob** [comment]
It solved the issue. Thank you
