### ISSUE TITLE
ZTH02 offset adjustment

### ISSUE THREAD

**Issue by philrich123** [pvvx/BLE_THSensor#14]
Hi,

My zigbee ZTH02 works perfectly with this firmware, thanks...

I just have to adjust the offset !
Is there a way to adjust temperature and humidity offset for ZTH02 ?
zigbee command or something else.

Thanks

**Comment by pvvx** [comment]
> zigbee command or something else.

https://github.com/pvvx/ZigbeeTLc?tab=readme-ov-file#additional-settings


#ATTENTION: Starting from version 4.8, support and code for the described models moved to https://github.com/pvvx/ATC_MiThermometer!

**Comment by philrich123** [comment]
Hi,

Yes I have read this.
I have understood that version 4.8 for ZTH02 is only BLE (no ".bin" with zigbee version).
So I have flashed with https://raw.githubusercontent.com/pvvx/ZigbeeTLc/master/bin/ZTH02Z_v0123.bin (the zigbee firmware proposed by the Telink flasher utility).
am I right ?

But ith this zigbee firmware Cluster 0x0204 Attr 0x0100 and 0x0101 doesn't seems to be available.
I get  a "UNSUPPORTED_ATTRIBUTE" status message (status 134) when trying to write !

Regards,

**Comment by pvvx** [comment]
For firmware version 0.1.2.1+ https://github.com/pvvx/ZigbeeTLc/issues/30#issue-2034396126

https://github.com/pvvx/ZigbeeTLc?tab=readme-ov-file#additional-settings
https://github.com/pvvx/ZigbeeTLc/blob/master/z2m/zigbeetlc_v0121.js

Perhaps a large interval is set "Attr: 0x0107, UINT8 (id:0x20), Measurement interval, range: 3..255 seconds. Default 10 seconds." The device communicates less frequently and then it is advisable to repeat the write command...

**Comment by philrich123** [comment]
Ok it works,
After several tests I had to swap MSB LSB for : 
- Attr 
- int16 offset

But not the cluster ID

Thanks for this nice firmware !
