### ISSUE TITLE
USB to serial adapter(rs 232) - which pins to use?

### ISSUE THREAD

**Issue by khayamgondal** [pvvx/BLE_THSensor#6]
I have this USB to serial adapter. Which pins do I need to connect to the Telink SoC ? 
![PXL_20231122_151907799](https://github.com/pvvx/BLE_THSensor/assets/2544495/00699c09-213a-4fa3-83b9-988953affc1a)
![PXL_20231122_151858598 MP](https://github.com/pvvx/BLE_THSensor/assets/2544495/583a4385-fa6a-4938-8c79-2fa5ef7d5ab7)

**Comment by pvvx** [comment]
Requires a USB to UART adapter with TTL 3.3V outputs.
